version: '3.8'

services:
  n8n-main:
    image: n8nio/n8n:latest
    restart: always
    container_name: electus-n8n
    environment:
      - N8N_HOST=${N8N_HOST}
      - N8N_PORT=${N8N_PORT}
      - N8N_PROTOCOL=${N8N_PROTOCOL}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - DB_POSTGRESDB_HOST=n8n-postgres
      - DB_POSTGRESDB_DATABASE=${DB_POSTGRESDB_DATABASE}
      - DB_POSTGRESDB_USER=${DB_POSTGRESDB_USER}
      - DB_POSTGRESDB_PASSWORD=${DB_POSTGRESDB_PASSWORD}
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - REDIS_HOST=redis
      - QUEUE_BULL_REDIS_HOST=redis
      - EXECUTIONS_MODE=queue
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - n8n_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n-http.rule=Host(`${N8N_HOST}`)"
      - "traefik.http.routers.n8n-http.entrypoints=http"
      - "traefik.http.routers.n8n-http.middlewares=https-redirect"
      - "traefik.http.routers.n8n-https.rule=Host(`${N8N_HOST}`)"
      - "traefik.http.routers.n8n-https.entrypoints=https"
      - "traefik.http.routers.n8n-https.tls=true"
      - "traefik.http.services.n8n.loadbalancer.server.port=5678"

  n8n-worker:
    image: n8nio/n8n:latest
    restart: always
    container_name: electus-n8n-worker
    command: n8n worker
    environment:
      - DB_POSTGRESDB_HOST=n8n-postgres
      - DB_POSTGRESDB_DATABASE=${DB_POSTGRESDB_DATABASE}
      - DB_POSTGRESDB_USER=${DB_POSTGRESDB_USER}
      - DB_POSTGRESDB_PASSWORD=${DB_POSTGRESDB_PASSWORD}
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - REDIS_HOST=redis
      - QUEUE_BULL_REDIS_HOST=redis
      - EXECUTIONS_MODE=queue
    networks:
      - n8n_network

  n8n-postgres:
    image: postgres:15
    restart: always
    container_name: electus-n8n-postgres
    environment:
      - POSTGRES_USER=${DB_POSTGRESDB_USER}
      - POSTGRES_PASSWORD=${DB_POSTGRESDB_PASSWORD}
      - POSTGRES_DB=${DB_POSTGRESDB_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - n8n_network

  redis:
    image: redis:6-alpine
    restart: always
    container_name: electus-redis
    networks:
      - n8n_network

volumes:
  n8n_data:
  postgres_data:

networks:
  n8n_network:
